name: check

on:
  push:
    branches: [main]

  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    name: Node ${{ matrix.node-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing dev dependencies
        run: npm install

      - name: Checking formatting
        run: npm run check

      - name: Linting
        run: npm run lint
